Repository antlr/antlr4-lab, pull requests merged in 2022-10, with the labels that each got.

#19 Ace for input
  static/css/style.css
  static/index.html
  static/js/antlr-client.js
Labels: enhancement

#29 Right pane cleanup
  static/css/style.css
  static/index.html
  static/js/antlr-client.js
Labels: enhancement, editor

#28 Support Docker
  Dockerfile
  pom.xml
Labels: enhancement, build

#30 Drag n drop
  static/css/style.css
  static/js/antlr-client.js
Labels: feature request

#33 chore: fix typo
  README.md
Labels: documentation, enhancement

#37 pull width/height out of PS file in manner of @kaby76's https://githu…
  src/org/antlr/v4/server/ANTLRHttpServer.java
  src/org/antlr/v4/server/GrammarProcessor.java
Labels: bug
